name: Auto Create Pull Request to Production Fork

#on:
#  push:
#    branches:
#      - master

on: 
  workflow_dispatch:
  schedule:
  - cron: "* * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Sync and merge upstream repository with your current repository
  # You may pin to the exact commit or the version.
  # uses: dabreadman/sync-upstream-repo@fc5fe9952946b1daaafd9abd7fcd7e260b81ddbe
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
    # URL of gitHub public upstream repo
          upstream_repo: https://github.com/sadeshwar94/Express-BS-FE
    # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: master
    # Branch to merge into downstream
          downstream_branch: master
          token: $ {{ secrests.PROD_FORK_PAT}}
