name: Auto Create Pull Request to Production Fork

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Create Pull Request to Production Fork
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PROD_FORK_PAT }}
          repository: sadeshwar-mh/Express-BS-FE  # Target repo
          title: 'Automated Update from Developer Master'
          body: 'This is an automated pull request to merge changes from the developer repositorys master branch.'
          head: master  # Source branch in the current repository
          base: master  # Target branch in the production fork
          commit-message: 'Automated update from developer master'
