name: Create PR to Forked Repository

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: master
        destination_branch: master
        pr_title: "Update from upstream"
        pr_body: "This is an automated pull request from the development repository to sync with the forked master branch."
        github_token: ${{secrets.GB_TOKEN}}
        destination_repo: sadeshwar-mh/Express-BS-FE
